### ISSUE TITLE
buildPlugin RuntimeException

### ISSUE THREAD

**Issue by hanhuiATlocalhost** [fkorotkov/intellij-thrift#118]
`> Task :thrift:buildSearchableOptions
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.awt.EventQueue.dispatchEvent(java.awt.AWTEvent)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-04-07 21:54:11,060 [   1973]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2021-04-07 21:54:11,868 [   2781]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.intellij] 
Searchable options index builder completed
2021-04-07 21:54:26,885 [  17798]  ERROR - tellij.openapi.util.ObjectTree - Memory leak detected: 'org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab@62595b48' of class org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab@62595b48' of class org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:223)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:156)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:198)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:215)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:621)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:580)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:569)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:82)
	at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:245)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:244)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:31)
	at com.intellij.openapi.util.ObjectTree.createNodeFor(ObjectTree.java:99)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:60)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.openapi.ui.ComponentValidator.installOn(ComponentValidator.java:154)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.createVersionValidator(KotlinCompilerConfigurableTab.java:776)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.createUIComponents(KotlinCompilerConfigurableTab.java:751)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.$$$setupUI$$$(KotlinCompilerConfigurableTab.java)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.<init>(KotlinCompilerConfigurableTab.java:131)
	at org.jetbrains.kotlin.idea.compiler.configuration.KotlinCompilerConfigurableTab.<init>(KotlinCompilerConfigurableTab.java:174)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:704)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:754)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:425)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:332)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:171)
	at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:82)
	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:52)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:98)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:81)
	... 32 more
2021-04-07 21:54:26,886 [  17799]  ERROR - tellij.openapi.util.ObjectTree - IntelliJ IDEA 2020.3.3  Build #IC-203.7717.56 
2021-04-07 21:54:26,887 [  17800]  ERROR - tellij.openapi.util.ObjectTree - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-04-07 21:54:26,888 [  17801]  ERROR - tellij.openapi.util.ObjectTree - OS: Mac OS X 
2021-04-07 21:54:26,888 [  17801]  ERROR - tellij.openapi.util.ObjectTree - Plugin to blame: Kotlin version: 203-1.4.10-release-IJ7717.8 
`

**Comment by hanhuiATlocalhost** [comment]
I have upgraded the latest plugin
