### ISSUE TITLE
Broken with IDEA 14.1

### ISSUE THREAD

**Issue by akaspin** [fkorotkov/intellij-thrift#40]
When I upgrade IDEA to 14.1 - I get tons of errors:

```
null
java.lang.NullPointerException
    at com.intellij.plugins.thrift.lang.psi.presentation.ThriftTopLevelDeclarationPresentationProvider$1.getLocationString(ThriftTopLevelDeclarationPresentationProvider.java:27)
    at com.intellij.ide.projectView.PresentationData.updateFrom(PresentationData.java:184)
    at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:588)
    at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
    at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:892)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3012)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$33$1.run(AbstractTreeUi.java:1728)
    at com.intellij.ide.util.treeView.AbstractTreeUi$35.perform(AbstractTreeUi.java:1818)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1815)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5300(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2091)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:62)
    at com.intellij.ide.util.treeView.AbstractTreeUi$38$1.perform(AbstractTreeUi.java:1983)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2186)
    at com.intellij.ide.util.treeView.AbstractTreeUi$38.perform(AbstractTreeUi.java:1978)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
    at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
    at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
    at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

But all works.

**Comment by akaspin** [comment]
Anybody there?

**Comment by jcdavis** [comment]
Odd, I haven't seen anything like this. Is it easily repro-able?

**Comment by akaspin** [comment]
IDEA 14.1, create new module, add thrift facet, new thrift file... on first syntax error...

**Comment by akaspin** [comment]
```
2015-05-26 20:14:18,671 [    834]   INFO - ps.incremental.BuilderRegistry - com.intellij.plugins.thrift.jps.ThriftBuilder builder returns 'null' from 'getCompilableFileExtensions' method so files for module-level builders won't be filtered
```
