### ISSUE TITLE
Thrift compiler runs under project JDK

### ISSUE THREAD

**Issue by TV4Fun** [fkorotkov/intellij-thrift#46]
For reasons which I don't understand, the Thrift plugin, when compiling, runs something using the project's JDK version. So for instance, if I have a project that is using JDK 1.7, when I try to compile I get this error from Thrift:

Error:Internal error: (java.lang.UnsupportedClassVersionError) com/intellij/plugins/thrift/jps/ModelSerializerExtension : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/intellij/plugins/thrift/jps/ModelSerializerExtension : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
    at com.intellij.util.containers.ContainerUtilRt.copy(ContainerUtilRt.java:179)
    at com.intellij.util.containers.ContainerUtilRt.newArrayList(ContainerUtilRt.java:168)
    at org.jetbrains.jps.plugin.impl.JpsPluginManagerImpl.loadExtensions(JpsPluginManagerImpl.java:18)
    at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:59)
    at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:46)
    at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.getSdkPropertiesSerializer(JpsSdkTableSerializer.java:205)
    at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdk(JpsSdkTableSerializer.java:99)
    at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdks(JpsSdkTableSerializer.java:80)
    at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:144)
    at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:137)
    at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:61)
    at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:83)
    at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:73)
    at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalSettings(JpsGlobalLoader.java:59)
    at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:38)
    at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:45)
    at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:78)
    at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:266)
    at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
    at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
    at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

If I change the project's JDK to 1.8, this error goes away, but then I have other problems with my 1.7 project. The only solution I have found to this is to disable the thrift plugin.

**Comment by TV4Fun** [comment]
This was under idea 2016.1.1 under OSX by the way.

**Comment by Lhfcws** [comment]
I have this problem too. my stacktrace is totally the same as @TV4Fun 's.
ENV: idea build IU-145.258 on OSX 10.11, system thrift 0.9.3, JDK 1.7.0_75.
And I was trying to compile a project without any relation to thrift.

**Comment by philltomlinson** [comment]
Same issue here. 2016.1.1 using Windows 7.

**Comment by junchaowu** [comment]
same

**Comment by russellpwirtz** [comment]
Same here -- Mac 10.11.4, project requires Java 1.7. Disabling the thrift plugin allows the project to build.

**Comment by jrhizor** [comment]
Same issue, Mac 10.10.3, Idea 2016.1.2.

**Comment by pablonautic** [comment]
Same for me, IntelliJ IDEA 2016.1.2 on Win10, project using Java 1.7.

**Comment by SinghAsDev** [comment]
Another victim here :(.

**Comment by xBlackCat** [comment]
Unfortunatelly, https://youtrack.jetbrains.com/issue/IDEA-127825

We could re-open the issue together and break the wall! :)

**Comment by geckhan** [comment]
same problem.....

**Comment by nesuk** [comment]
@TV4Fun This issue is imported by the `thrift` plugin, which only support JDK8 now. 
Try uninstall the plugin.

**Comment by allquantor** [comment]
same here

**Comment by fkorotkov** [comment]
I think it was fixed in https://github.com/fkorotkov/intellij-thrift/commit/41e8d05dc58468ef701573750ffacfc6b469cb38 aka version 0.9.6

**Comment by Lhfcws** [comment]
Actually it might be fixed in 0.9.7 . 0.9.7 was released at 2017.08.30. 
I've tested the previous version (it should be 0.9.6, but I did not identify it)  a few days just before this comment , and it failed. 


I reinstalled the plugin today and seems that it works!
 
ENV: idea ultimate 2017.2.2 on macos

**Comment by fkorotkov** [comment]
Sweet! Thank you for checking!

**Comment by zxeoc** [comment]
It seems this happened again.
`Internal error (java.lang.UnsupportedClassVersionError): com/intellij/plugins/thrift/jps/ModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: com/intellij/plugins/thrift/jps/ModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.intellij.util.containers.ContainerUtilRt.copy(ContainerUtilRt.java:113)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:205)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:113)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:105)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:58)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:47)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.getRootType(JpsLibraryTableSerializer.java:98)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibrary(JpsLibraryTableSerializer.java:69)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibrary(JpsLibraryTableSerializer.java:46)
	at org.jetbrains.jps.model.serialization.library.JpsLibraryTableSerializer.loadLibraries(JpsLibraryTableSerializer.java:41)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$GlobalLibrariesSerializer.loadExtension(JpsGlobalLoader.java:113)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$GlobalLibrariesSerializer.loadExtension(JpsGlobalLoader.java:106)
	at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:46)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:80)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:70)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalSettings(JpsGlobalLoader.java:43)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:21)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:34)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:64)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:279)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

`

I tried disabling the plugin, but another plugin(Erlang plugin from Sergey Ignatov, if someone interests) report a similar issue. So, maybe it's from IDEA?
