### ISSUE TITLE
Worker exited due to exception: com/intellij/util/indexing/IndexId

### ISSUE THREAD

**Issue by einverne** [fkorotkov/intellij-thrift#58]
version: 0.9.7

Each time I use Class search, thrift support plugin make IDE crash. Following is details.

```
Worker exited due to exception: com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at com.intellij.plugins.thrift.ThriftClassContributor.getNames(ThriftClassContributor.java:21)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:111)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:95)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:32)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:29)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1055)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:61)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:136)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:77)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1552)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1531)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1513)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1494)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1485)
	at com.intellij.openapi.project.DumbService$1.run(DumbService.java:94)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:136)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:130)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:91)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1485)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:199)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:196)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:219)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[com.intellij.plugins.thrift, 0.9.7]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more
```

**Comment by fkorotkov** [comment]
@einverne which IDE and which version of the IDE are you using?

**Comment by einverne** [comment]
I am using

```
IntelliJ IDEA 2016.3.5
Build #IU-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by u650080** [comment]
Same problem with 0.9.8 and IntelliJ IDEA 2016.3.8
