### ISSUE TITLE
Plugin is incompatible with IntelliJ IDEA 2019.2

### ISSUE THREAD

**Issue by chashnikov** [fkorotkov/intellij-thrift#74]
When the plugin is installed into IntelliJ IDEA 2019.2 it causes an exception (see below). This happens because the plugin uses `compileServer.plugin` extension from Java support but doesn't declare dependency on Java plugin. It worked in previous versions of IntelliJ IDEA because the Java support was bundled into the platform part of the IDE, but since 2019.2 Java support is extracted to a separate plugin so you need to explicitly declare dependency on Java, see [this blog post](https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/) for details. If you want to keep compatibility with non-Java IDEs, you can declare `compileServer.plugin` in a separate config file and use it with an optional dependency on Java plugin.

```
2019-08-13 19:01:21,592 [   3080]  ERROR - nsions.impl.ExtensionPointImpl - java.lang.ClassNotFoundException: com.intellij.compiler.server.CompileServerPlugin PluginClassLoader[com.intellij.plugins.thrift, 0.9.9] com.intellij.ide.plugins.cl.PluginClassLoader@41e1b7c8 
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: java.lang.ClassNotFoundException: com.intellij.compiler.server.CompileServerPlugin PluginClassLoader[com.intellij.plugins.thrift, 0.9.9] com.intellij.ide.plugins.cl.PluginClassLoader@41e1b7c8
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:50)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:54)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:439)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:226)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:704)
	at com.intellij.jps.impl.JpsIdePluginManagerImpl.<init>(JpsIdePluginManagerImpl.java:38)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:91)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:73)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:46)
	at org.jetbrains.jps.model.serialization.module.JpsModuleRootModelSerializer.getSourceRootPropertiesSerializer(JpsModuleRootModelSerializer.java:187)
	at org.jetbrains.jps.model.serialization.module.JpsModuleRootModelSerializer.loadSourceRoot(JpsModuleRootModelSerializer.java:170)
	at org.jetbrains.kotlin.idea.roots.KotlinNonJvmSourceRootConverterProvider$ConverterImpl$createModuleFileConverter$1.isConversionNeeded(KotlinNonJvmSourceRootConverterProvider.kt:188)
	at org.jetbrains.kotlin.idea.roots.KotlinNonJvmSourceRootConverterProvider$ConverterImpl$createModuleFileConverter$1.isConversionNeeded(KotlinNonJvmSourceRootConverterProvider.kt:135)
	at com.intellij.conversion.impl.ConversionRunner.isConversionNeeded(ConversionRunner.java:69)
	at com.intellij.impl.ConversionServiceImpl.isConversionNeeded(ConversionServiceImpl.java:173)
	at com.intellij.impl.ConversionServiceImpl.convert(ConversionServiceImpl.java:114)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:589)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.intellij.compiler.server.CompileServerPlugin PluginClassLoader[com.intellij.plugins.thrift, 0.9.9] com.intellij.ide.plugins.cl.PluginClassLoader@41e1b7c8
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:94)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:38)
	... 42 more
Caused by: java.lang.ClassNotFoundException: com.intellij.compiler.server.CompileServerPlugin PluginClassLoader[com.intellij.plugins.thrift, 0.9.9] com.intellij.ide.plugins.cl.PluginClassLoader@41e1b7c8
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:91)
	... 43 more
Caused by:
```

**Comment by fkorotkov** [comment]
Fixed in #75
