### ISSUE TITLE
Idea 2019.3 beta2:Cannot add 'thrift-jps.jar' from 'Thrift Support 1.0' to compiler classpath

### ISSUE THREAD

**Issue by afsfge** [fkorotkov/intellij-thrift#84]
you can reproduce by restarting idea 

java.lang.Throwable: Cannot add 'thrift-jps.jar' from 'Thrift Support 1.0' to compiler classpath
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.computeCompileServerPluginsClasspath(BuildProcessClasspathManager.java:120)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getStaticClasspath(BuildProcessClasspathManager.java:48)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:34)
	at com.intellij.compiler.server.BuildManager.launchBuildProcess(BuildManager.java:1238)
	at com.intellij.compiler.server.BuildManager.lambda$null$10(BuildManager.java:799)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

![Xnip2019-11-19_11-14-50](https://user-images.githubusercontent.com/17295616/69113697-b3831e00-0abe-11ea-8269-af20c56881ba.jpg)

**Comment by fkorotkov** [comment]
I don't see Beta 2 available. Which exact version are you using? I don't see the exception in my IntelliJ Community Edition:

```
IntelliJ IDEA 2019.3 EAP (Community Edition)
Build #IC-193.5233.12, built on November 13, 2019
```

**Comment by afsfge** [comment]
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.5233.12, built on November 13, 2019
IntelliJ IDEA EAP User
Expiration date: December 13, 2019
Runtime version: 11.0.4+10-b520.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

You can download this version from the url below:
https://www.jetbrains.com/idea/nextversion/
Also,you can use JetBrains ToolBox to install this version

**Comment by lukaszwawrzyk** [comment]
I believe I fixed it here: https://github.com/fkorotkov/intellij-thrift/pull/90
